"""
core/email_reporter.py — Send full lead intelligence reports via email
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
import config

logger = logging.getLogger(__name__)


def send_lead_report(lead: dict, web_intel: dict, opportunity: dict, outreach_draft: str) -> bool:
    """
    Send a full lead intelligence report via email.
    Returns True if sent successfully.
    """
    if not config.EMAIL_ENABLED:
        logger.debug("[EmailReporter] Email not configured.")
        return False

    subject = f"[{opportunity['priority']}] {lead.get('niche', '').replace('_', ' ').upper()} LEAD: {lead.get('title', 'Unknown')[:55]}"
    body = _build_report(lead, web_intel, opportunity, outreach_draft)

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = config.EMAIL_USER
        msg["To"] = config.EMAIL_USER
        msg.attach(MIMEText(body, "plain", "utf-8"))

        with smtplib.SMTP(config.EMAIL_HOST, config.EMAIL_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.login(config.EMAIL_USER, config.EMAIL_PASS)
            server.sendmail(config.EMAIL_USER, config.EMAIL_USER, msg.as_string())

        logger.info(f"[EmailReporter] Report sent: {lead.get('title', '')[:50]}")
        return True
    except Exception as e:
        logger.error(f"[EmailReporter] Failed to send: {e}")
        return False


def _build_report(lead: dict, web_intel: dict, opportunity: dict, outreach_draft: str) -> str:
    missing = "\n".join(f"  - {m}" for m in web_intel.get("signals_missing", [])) or "  None detected"
    found   = "\n".join(f"  - {s}" for s in web_intel.get("signals_found", [])) or "  None"
    scoring = "\n".join(f"  - {r}" for r in opportunity.get("reasoning", [])) or "  N/A"
    niche   = lead.get("niche", "N/A").replace("_", " ").title()

    return f"""
LEAD INTELLIGENCE REPORT
=========================

IDENTITY
--------
Name / Title  : {lead.get('title', 'N/A')}
Niche         : {niche}
Location      : {lead.get('location', 'N/A')}
Organization  : {lead.get('company', 'N/A')}

CONTACT DETAILS
---------------
Website  : {lead.get('url', 'N/A')}
Email    : {lead.get('email', 'N/A')}
LinkedIn : {lead.get('linkedin', 'N/A')}
Phone    : {lead.get('phone', 'N/A')}

SCORING
-------
Lead Score        : {lead.get('score', 0)}/10
Opportunity Score : {opportunity.get('opportunity_score', 0)}/10
Priority Level    : {opportunity.get('priority', 'LOW')}

Score Breakdown:
{scoring}

WEBSITE INTELLIGENCE
--------------------
Website Accessible : {'Yes' if web_intel.get('accessible') else 'No'}
Has Chatbot        : {'Yes' if web_intel.get('has_chatbot') else 'NO - OPPORTUNITY'}
Has Booking System : {'Yes' if web_intel.get('has_booking') else 'NO - OPPORTUNITY'}
Has Contact Form   : {'Yes' if web_intel.get('has_contact_form') else 'NO - OPPORTUNITY'}
Modern Website     : {'Yes' if web_intel.get('is_modern') else 'Outdated'}

Signals Found:
{found}

Automation Gaps (Your Opportunities):
{missing}

DESCRIPTION
-----------
{lead.get('description', 'N/A')}

OUTREACH DRAFT
--------------
{outreach_draft}

---
Generated by SAFE MODE AI REVENUE ENGINE
    """.strip()
