"""
core/pdf_reporter.py — Generate PDF lead intelligence reports
Uses fpdf2 (pure Python, no system dependencies)
"""
from fpdf import FPDF
import io


def _safe(text) -> str:
    """Strip non-latin chars that fpdf built-in fonts can't render."""
    return str(text or "N/A").encode("latin-1", errors="replace").decode("latin-1")


def generate_lead_pdf(lead: dict, web_intel: dict, opportunity: dict, outreach: str) -> bytes:
    """
    Generate a PDF report for a single lead.
    Returns PDF as bytes.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    niche    = lead.get("niche", "").replace("_", " ").upper()
    priority = opportunity.get("priority", "LOW")
    title    = _safe(lead.get("title", "Unknown"))

    # ── Header ──────────────────────────────────────────────────────────────
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, f"{priority} OPPORTUNITY LEAD", fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, f"Niche: {niche}  |  Generated by AI Lead Intelligence System", fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Identity ─────────────────────────────────────────────────────────────
    _section_header(pdf, "IDENTITY")
    _row(pdf, "Name / Title",   title)
    _row(pdf, "Niche",          niche.title())
    _row(pdf, "Location",       _safe(lead.get("location", "")))
    _row(pdf, "Organization",   _safe(lead.get("company", "")))
    pdf.ln(3)

    # ── Contact Details ───────────────────────────────────────────────────────
    _section_header(pdf, "CONTACT DETAILS")
    _row(pdf, "Website",  _safe(lead.get("url", "")))
    _row(pdf, "Email",    _safe(lead.get("email", "")))
    _row(pdf, "LinkedIn", _safe(lead.get("linkedin", "")))
    _row(pdf, "Phone",    _safe(lead.get("phone", "")))
    pdf.ln(3)

    # ── Scores ────────────────────────────────────────────────────────────────
    _section_header(pdf, "SCORING")

    lead_score = lead.get("score", 0)
    opp_score  = opportunity.get("opportunity_score", 0)

    # Score bars
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(55, 8, "Lead Score:")
    _score_bar(pdf, lead_score)
    pdf.ln(1)

    pdf.cell(55, 8, "Opportunity Score:")
    _score_bar(pdf, opp_score)
    pdf.ln(1)

    priority_colors = {"HIGH": (220, 50, 50), "MEDIUM": (230, 160, 30), "LOW": (100, 150, 100)}
    r, g, b = priority_colors.get(priority, (80, 80, 80))
    pdf.set_text_color(r, g, b)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Priority: {priority}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(30, 30, 30)
    pdf.ln(2)

    if opportunity.get("reasoning"):
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, "Score Breakdown:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for reason in opportunity["reasoning"]:
            pdf.cell(8)
            pdf.cell(0, 5, _safe(f"* {reason}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Website Intelligence ──────────────────────────────────────────────────
    _section_header(pdf, "WEBSITE INTELLIGENCE")
    _row_bool(pdf, "Website Accessible",  web_intel.get("accessible"))
    _row_bool(pdf, "Has Chatbot",         web_intel.get("has_chatbot"))
    _row_bool(pdf, "Has Booking System",  web_intel.get("has_booking"))
    _row_bool(pdf, "Has Contact Form",    web_intel.get("has_contact_form"))
    _row_bool(pdf, "Modern Website",      web_intel.get("is_modern"))

    if web_intel.get("signals_missing"):
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(180, 60, 60)
        pdf.cell(0, 5, "Automation Gaps (Your Opportunities):", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for gap in web_intel["signals_missing"]:
            pdf.cell(8)
            pdf.cell(0, 5, _safe(f"* {gap}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(30, 30, 30)
    pdf.ln(3)

    # ── Description ──────────────────────────────────────────────────────────
    _section_header(pdf, "DESCRIPTION")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, _safe(lead.get("description", "No description available.")))
    pdf.ln(3)

    # ── Outreach Draft ────────────────────────────────────────────────────────
    _section_header(pdf, "AI-GENERATED OUTREACH DRAFT")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(0, 5, _safe(outreach), fill=True)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by SAFE MODE AI Lead Intelligence System", align="C", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


# ── Helpers ──────────────────────────────────────────────────────────────────

def _section_header(pdf: FPDF, title: str):
    pdf.set_fill_color(50, 50, 120)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(30, 30, 30)
    pdf.ln(2)


def _row(pdf: FPDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(45, 6, f"{label}:")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 6, value or "N/A")


def _row_bool(pdf: FPDF, label: str, value: bool):
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(50, 6, f"{label}:")
    pdf.set_font("Helvetica", "", 9)
    if value:
        pdf.set_text_color(60, 150, 60)
        pdf.cell(0, 6, "Yes", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_text_color(180, 60, 60)
        pdf.cell(0, 6, "No", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(30, 30, 30)


def _score_bar(pdf: FPDF, score: int):
    """Draw a visual score bar."""
    bar_w = 8
    for i in range(10):
        if i < score:
            pdf.set_fill_color(50, 180, 80)
        else:
            pdf.set_fill_color(220, 220, 220)
        pdf.cell(bar_w, 6, "", fill=True, border=1)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(12, 6, f" {score}/10", new_x="LMARGIN", new_y="NEXT")
